Repository aeiou80/Mini-SurveyMonkey-4806, pull requests merged in 2022-03, with the labels that each got.

#6 Configure CORS
  src/main/java/com/example/demo/Application.java
Labels: enhancement

#9 DB schema and updated README
  README.md
  src/images/DB_Schema.png
  src/images/dbdiagramio.txt
Labels: documentation

#13 Fix CORS
  src/main/java/com/example/demo/Application.java
  src/main/java/com/example/demo/WebSecurityConfig.java
Labels: bug

#15 Possible Cors fix on production
  src/main/java/com/example/demo/Application.java
  src/main/java/com/example/demo/WebSecurityConfig.java
Labels: bug

#19 Close Survey
  src/main/java/com/example/demo/controller/AnswersController.java
  src/main/java/com/example/demo/controller/SurveyController.java
  src/main/java/com/example/demo/model/Answer.java
  src/main/java/com/example/demo/model/Question.java
  src/main/java/com/example/demo/model/Survey.java
  src/main/java/com/example/demo/repository/SurveyProjection.java
  src/main/java/com/example/demo/repository/SurveysRepository.java
  src/test/java/com/example/demo/AnswersTest.java
  src/test/java/com/example/demo/SurveyTest.java
Labels: enhancement
